### ISSUE TITLE
Test suite passes even if clause 2.3.2 is not implemented

### ISSUE THREAD

**Issue by abdulapopoola** [promises-aplus/promises-tests#71]
I removed the entire implementation of 2.3.2 from my promise implementation (adehunJS) and still got the full suite to pass.

Is this a test hole? Wrong implementations can also cause the test suite to pass.

**Comment by domenic** [comment]
2.3.2 is actually redundant with 2.3.3, in the sense that implementing 2.3.3 will also implement 2.3.2. (But, implementing 2.3.2 does not imply implementing 2.3.3.) The reason it exists is that we want to allow people to go down different paths for known-promises vs. other thenables.

So, this is entirely as expected. If we removed 2.3.2, then we would add some tests ensuring that even known-promises go down the promise resolution procedure path. So it's more about governing what tests are _not_ there, than about adding tests for it.
