### ISSUE TITLE
Add tests for Promise.all and Promise.race.

### ISSUE THREAD

**Issue by joeyparrish** [promises-aplus/promises-tests#77]
As these are important parts of a Promise polyfill, it would be great to have tests for them in the suite.  Would this be considered in scope for this project?

**Comment by domenic** [comment]
Nope. This is a test suite for the [Promises/A+](https://promisesaplus.com/) spec, which only specifies the minimum needed for interoperability (the `then` method). If you're interested in a test suite for standard ES2015 promises, [test262](https://github.com/tc39/test262/) is probably what you're interested in.
