### ISSUE TITLE
"just create a pull request"

### ISSUE THREAD

**Issue by RonNewcomb** [promises-aplus/promises-tests#82]
https://promisesaplus.com/implementations  says to get an implementation on that page to just submit a pull request, presumably here, but pull requests don't seem work across different people's folders.

Anyway, I'd like to submit  https://github.com/RonNewcomb/promise   as a Conformant Promises/A+ implementation.

**Comment by briancavalier** [comment]
Hi @RonNewcomb.  Nice work.  To add your implementation, submit a PR to the [promises-spec](https://github.com/promises-aplus/promises-spec) repository where you update the [implementations.md file](https://github.com/promises-aplus/promises-spec/blob/master/implementations.md) with a link to your implementation's repository.

**Comment by RonNewcomb** [comment]
Oh I see. Done. And thank you.
