### ISSUE TITLE
Promise.prototype.finally tests

### ISSUE THREAD

**Issue by Andarist** [promises-aplus/promises-tests#86]
Is this test suite gonna port them from the spec repo - https://github.com/tc39/proposal-promise-finally/blob/master/test/test.js ? Or there is not such intent? I'd like to have a programmatic test suite to reuse in 1 of the Promise implementations, ain't sure though if this should be included here or should I raise and issue on the spec boards?

**Comment by domenic** [comment]
No, finally (and catch) are not part of Promises/A+.
