### ISSUE TITLE
2.3.3 numberOfTimesThenWasRetrieved should not increment in then getter

### ISSUE THREAD

**Issue by zWingz** [promises-aplus/promises-tests#88]
it should increment when 'then' called.?
but it increment when 'then' got.

```javascript 
// it will trigger then's getter twice, but call once
if (val && _isFunction(val.then)) {
   val.then(resolve, reject)
} else {
   fnc(val)
 }
```

**Comment by domenic** [comment]
Nope, this is intentionally testing that you only trigger the getter once. You need to save the result: `const then = val.then`.
